# Generated by Django 4.2 on 2024-03-16 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('blurb', models.TextField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.TextField()),
                ('photo', models.ImageField(default='static/icons/review_small.png', upload_to='')),
                ('review', models.TextField()),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
