# Generated by Django 4.2 on 2024-03-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='photo',
            field=models.ImageField(default='static/icons/review_small.png', upload_to='media'),
        ),
    ]
