# Generated by Django 4.2 on 2024-03-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0003_alter_reviewmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
